### ISSUE TITLE
CP login page inaccessible when Lockout is enabled

### ISSUE THREAD

**Issue by wihodges** [jalendport/craft-lockout#1] opened 2019-12-03 20:51 UTC
If lock is enabled. There is no ability to login for any type of user - or at least that's what happens when I open site.com/admin from a private window or sign out of admin user.

Also it's great to be able to customize the lock message, and it would be nice to also be able to customize the "Unauthorized" headline of the message. 

Another edge problem that cropped up for me, since I use "dashboard begone" there isn't a non CLI way to disable/enable. The CLI however is much nicer method anyways. Could be interesting to have some custom environment based config file option or project.yaml setting update. 

Thanks for the plugin btw, hope feedback is useful.

**Comment by jalendport** [comment] 2019-12-11 02:38
Hey Will, thanks for the feedback! It's definitely appreciated...

I'm able to reproduce what you're describing where you can't access the login page when Lockout is enabled. I'll push an update shortly to resolve that.

---

> Also it's great to be able to customize the lock message, and it would be nice to also be able to customize the "Unauthorized" headline of the message.

As far as I know it's impossible to change the headline on the [403 template](https://github.com/craftcms/cms/blob/ecef77daa1bab6cd69de97d1b3d7b48f64de1e2e/src/templates/403.html). I haven't tested this, but it's possible you could use a custom 403 template in the same way you create a custom 404. Alternatively, I could add a setting that would allow you to select a template to redirect to.

---

> since I use "dashboard begone" there isn't a non CLI way to disable/enable.

Is there a non-CLI non-dashboard way you'd like to see added? I'm open to suggestions... (FYI if you're in an environment where `allowAdminChanges` is `true` you can enable/disable Lockout from the plugin settings.)

---

> Could be interesting to have some custom environment based config file option or project.yaml setting update.

The reason I opted for not using project config to store the settings was because of the pain point this plugin was solving in my own workflow. With project config I'd have to enable Lockout locally, do a git commit and a git push, and then a deployment since I can't access and change the settings in production (due to `allowAdminChanges` being `false` in that environment). I believe the other plugin settings are controlled via project config though, and if it would be helpful I can add a config file for those as well. However, I'm not seeing the benefit of storing the enable/disable setting in the project config. I would be interested though in hearing how storing it in the project config would be beneficial to your workflow because I definitely understand not everyone works exactly like I do!

**Comment by jalendport** [comment] 2020-01-03 18:15
This was resolved in 6d8b21beb6d3c11ab2abc06cd9b68ced10182455. If you have any further thoughts about the other three things you brought up that I responded too with my reasoning, feel free to open separate issues for those!

**Closed as completed by jalendport** 2020-01-03 18:15 UTC
Labels: bug
